version: '3.8'

services:
  memcached:
    image: memcached:1.4
    container_name: ymdot-memcached
  mysql:
    image: mysql:5.6
    container_name: ymdot_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=screencast
  php:
    image: php:5.6-fpm
    container_name: ymdot-php
    volumes:
      - ./www:/www
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf.default
      - ./php/exts:/usr/local/lib/php/extensions/no-debug-non-zts-20131226/
    links:
      - memcached
      - mysql
  nginx:
    image: nginx:stable
    container_name: ymdot_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./demo/www:/www
    links:
      - php
    ports:
      - 80:80


  